# Generated by Django 4.1.1 on 2022-09-10 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0002_alter_user_managers_user_is_administrador_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_administrador',
            new_name='is_usermain',
        ),
    ]
